# Generated by Django 4.1.4 on 2022-12-13 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.SlugField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file', models.FileField(upload_to='book_file', verbose_name='book_file')),
                ('slug', models.SlugField(blank=True, max_length=220, primary_key=True, serialize=False, verbose_name='Slug')),
                ('cover', models.ImageField(upload_to='book_cover')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('genre', models.ManyToManyField(related_name='genre', to='books.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_cover')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cover', to='books.books')),
            ],
        ),
    ]
