# Generated by Django 4.1.4 on 2022-12-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rating_bookstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(upload_to='book/cover'),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='book/file', verbose_name='book_file'),
        ),
        migrations.AlterField(
            model_name='bookstate',
            name='state',
            field=models.CharField(blank=True, choices=[('READED', 'прочитан'), ('READ_NOW', 'в процессе чтения'), ('PLANNING', 'пранируется к чтению')], max_length=250, null=True),
        ),
    ]
