# Generated by Django 4.1.4 on 2022-12-16 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_books_cover_alter_books_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='UserBookRating',
        ),
        migrations.RenameModel(
            old_name='BookState',
            new_name='UserBookState',
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
