# Generated by Django 4.1.4 on 2022-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_rating_userbookrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookstate',
            name='state',
            field=models.CharField(blank=True, choices=[('read_finished', 'прочитан'), ('read_process', 'в процессе чтения'), ('read_planning', 'пранируется к чтению')], max_length=250, null=True),
        ),
    ]
