version: '3.7'

services:
  redis:
    restart: always
    image: redis:7-alpine
    env_file:
      - ./.env
    volumes:
      - ./server/redis:/opt/redis
  database:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./server/database:/var/lib/postgresql
  database_admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - database
  django:
    build: ./server/src
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./server/src:/app
    depends_on:
      - database
      - redis
  celery:
    build: ./server/src
    command: >
      sh -c "celery -A config worker -l info"
    env_file:
      - ./.env
    volumes:
      - ./server/src:/app
    depends_on:
      - django
  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379 flower --port=5556
    ports:
      - 5556:5556
    depends_on:
      - redis
