# Generated by Django 4.1.4 on 2022-12-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Comments'},
        ),
    ]
